#%RAML 1.0 DataType

type: array
items:
  type: object
  properties:
    transaction_id : string
    instrument_id : string
    capture_amount?: number 
    refund_amount?: number 
    currency: string
    reason?: 
      enum:
        - authorization
        - revoke
        - refund
        - capture
    metadata?: !include metadata.raml
    payment_method?: string
    payment_wallet?: string
    created_at?: string
    processed_at?: string
