#%RAML 1.0 NamedExample

{
  "error_code": "internal_error",
  "message": "400 Bad Request. The request syntax/semantics is invalid. We will not retry this method to resolve this error",
  "details": {}
}
