#%RAML 1.0 NamedExample
[
  {
    "payment_method": "credit_card",
    "payment_wallet": "Apple Pay",
    "transaction_id": "unique for every transaction in this payload-revoke-12345",
    "instrument_id": "unique-psp-instrument-identifier-1234567890",
    "capture_amount": -100,
    "refund_amount": 0,
    "currency": "USD",
    "created_at": "0001-01-01T00:00:00Z",
    "processed_at": "0001-01-01T00:00:00Z",
    "reason": "revoke"
  }
]